Decouple BC Providers for cross-platform support
When testing on Windows, I found the error that stated:

```
PGPException: Exception encrypting key
...
Caused by: java.lang.SecurityException: JCE cannot authenticate the
provider BC
...
JarException: [filename] has unsigned entries -
com/themathjester/ExecuteDrm.class
```

According to some forum posts (and GitHub issues?), if we package the
`bc*.jar` files separately from our application JARs, these errors
dissipate. And sure enough, when putting these three BouncyCastle JARs
separately and setting them on the same (runtime) classpath, the
program executes correctly on Windows!

If you have a way to simplify this change, pray tell.

Source: https://coderanch.com/t/432801/